project:
  type: book
  output-dir: docs
  
book:
  title: "母平均の「補助線」の推定 (ver 0.1.2)"
  author: "川田恵介"
  date: now
  chapters:
    - index.qmd
    - model.qmd
    - population.qmd
    - OLS.qmd
    - PopulationOLS.qmd
    - LASSO.qmd
    - Reference.qmd
  appendices:
    - prediction.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    pdf-engine: lualatex
    documentclass: ltjsbook

execute:
  freeze: auto
  message: false
  warning: false
  echo: false
