project:
  type: book

book:
  title: "test"
  author: "Norah Jones"
  date: "10/16/2024"
  chapters:
    - index.qmd
    - prediction.qmd

bibliography: references.bib

format:
  html

execute:
  freeze: auto
  message: false
  warning: false
  echo: false
